"""Offline-first loading for the teaching datasets.

``load_data(module)`` returns the module's main table. If the derived file is
missing it is built on the spot from whatever raw files are present, so a
student who skipped a step gets a clear message naming the file to fetch rather
than a stack trace.

Modules that need a second table (module A's images, F's variant list, G's
sample annotations) get it from ``load_extra(module)``.
"""
from pathlib import Path

import pandas as pd

from data_registry import MODULES, SOURCES

# What each module's main table is, and how to describe it in the menu.
PRIMARY = {
    "A": "data/derived/a_oasis_visits.csv",
    "C": "data/derived/c_biomarkers.csv",
    "D": "data/derived/d_oasis_subjects.csv",
    "E": "data/derived/e_records.csv",
    "F": "data/derived/f_cohort.csv",
    "G": "data/derived/g_expression.csv",
    "H": "data/derived/h_bace.csv",
}


def repo_root():
    return next(parent for parent in [Path.cwd(), *Path.cwd().parents] if (parent / "src").exists())


def _missing_raw(module):
    return [key for key in MODULES[module]["sources"] if not (repo_root() / SOURCES[key]["path"]).exists()]


def ensure_prepared(module):
    """Build the derived files for a module if they are not there yet."""
    module = module.upper()
    root = repo_root()
    if all((root / name).exists() for name in MODULES[module]["derived"]):
        return
    missing = _missing_raw(module)
    if missing:
        wanted = "\n".join(f"    {SOURCES[key]['path']}   <- {SOURCES[key]['title']}" for key in missing)
        raise FileNotFoundError(
            f"Module {module} needs raw files that are not on this machine:\n{wanted}\n\n"
            "Run notebooks/00_download_data.ipynb (section 3), or copy these files from the\n"
            "instructor's USB stick / shared folder into the paths shown above."
        )
    import prepare

    prepare.prepare(module, force=True)


def load_data(module):
    """Return the module's main table as a DataFrame."""
    module = module.upper()
    if module not in PRIMARY:
        raise KeyError(f"Unknown module {module!r}; expected one of {', '.join(PRIMARY)}")
    ensure_prepared(module)
    return pd.read_csv(repo_root() / PRIMARY[module])


def load_extra(module):
    """Return the module's secondary artefacts as a dict, or an empty dict."""
    module = module.upper()
    ensure_prepared(module)
    root = repo_root()
    if module == "A":
        import images as image_helpers

        pictures, meta = image_helpers.load_slices()
        return {"images": pictures, **meta}
    if module == "F":
        return {"variants": pd.read_csv(root / "data/derived/f_variants.csv")}
    if module == "G":
        return {"samples": pd.read_csv(root / "data/derived/g_samples.csv")}
    return {}


def provenance(module):
    """A short paragraph on where this module's data came from — printed in each notebook."""
    module = module.upper()
    entry = MODULES[module]
    lines = [f"Module {module} — {entry['title']} ({entry['feasibility']})",
             f"  Real:      {entry['real']}",
             f"  Simulated: {entry['simulated']}"]
    for key in entry["sources"]:
        source = SOURCES[key]
        lines.append(f"  Source:    {source['title']}")
        lines.append(f"             {source['citation']}")
        lines.append(f"             Licence: {source['licence']}")
    if not entry["sources"]:
        lines.append("  Source:    none — this table is generated by src/simulate.py.")
    return "\n".join(lines)
